spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: micro
    password: micro
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8060

application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    product-url: http://localhost:8050/api/v1/product
    payment-url: http://localhost:8040/api/v1/payment