spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: micro
    password: micro
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

springdoc:
  version: 2.6.0
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    use-root-path: true

server:
  port: 8050
  forward-headers-strategy: framework



